stages:
    - name: Publish
      steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: example-django:${CICD_EXECUTION_SEQUENCE}
    - name: Deploy
      steps:
      - applyYamlConfig:
          path: ./deployment.yaml